version: '3'
services:
  app:
    build: ./
    restart: always
    container_name: app
    volumes:
      - ../:/var/www
    networks:
      - your-network
  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    tty: true
    ports:
      - "8000:80"
    volumes:
      - ../:/var/www
    networks:
      - your-network
    depends_on:
      - app
networks:
  your-network:
    driver: bridge